CREATE TABLE bandbridge_posts (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  post_type TEXT NOT NULL,
  location TEXT NOT NULL,
  style TEXT NOT NULL,
  commitment TEXT NOT NULL,
  skill_lvl TEXT NOT NULL,
  instruments_need TEXT NOT NULL,
  description TEXT NOT NULL, 
  date_created TIMESTAMP DEFAULT now() NOT NULL
);