CREATE TABLE bandbridge_users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_name TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL
);

ALTER TABLE bandbridge_posts
  ADD COLUMN 
    user_id INTEGER REFERENCES bandbridge_users(id)
    ON DELETE SET NULL;